# Generated by Django 2.0.3 on 2019-10-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_name'),
        ('orders', '0009_auto_20191019_0854'),
    ]

    operations = [
    ]
